version: '3.7'
services:
  wordpress:
    build :  ./requirements/WordPress/
    image: wordpress:img
    container_name: wordpress
    restart: on-failure
    ports:
      - "9000:80"
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/MariaDB/
    image: mariadb:img
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: on-failure
