version: '3.7'
services:
  nginx:
    networks:
      - xnetwork
    build: ./requirements/NGINX/
    image: nginx:img
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - testvol:/var/www/html
  wordpress:
    networks:
      - xnetwork
    build :  ./requirements/WordPress/
    image: wordpress:img
    container_name: wordpress
    restart: on-failure
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - testvol:/var/www/html
  mariadb:
    networks:
      - xnetwork
    build: ./requirements/MariaDB/
    image: mariadb:img
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - data_db:/var/lib/mysql/
volumes:
  testvol:
    driver: local
    driver_opts:
      type: none
      device: /home/ybadaoui/data/v1
      o: bind
  data_db:
    driver: local
    driver_opts:
      type: none
      device: /home/ybadaoui/data/v2
      o: bind
networks:
    xnetwork:
      driver: bridge