FROM debian

RUN apt-get update && apt-get upgrade -y && apt-get install php php-mysql php-fpm \
        php-curl php-gd php-intl php-mbstring php-soap php-xml php-xmlrpc php-zip -y \
        && apt install wget curl -y
RUN apt install vim -y
RUN apt install systemctl -y
#the following tree lines are for wp-cli installation
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
RUN mkdir -p /run/php/
# RUN chown www-data:www-data /var/www/html 
WORKDIR /var/www/html
RUN wp core download --allow-root
COPY tools/script.sh /var/www/html
RUN chmod +x /var/www/html/script.sh
RUN cp wp-config-sample.php wp-config.php
RUN rm wp-config-sample.php
ENTRYPOINT [ "./script.sh" ]