FROM debian

RUN apt-get update && apt-get upgrade -y && apt-get install php php-mysql php-fpm \
        php-curl php-gd php-intl php-mbstring php-soap php-xml php-xmlrpc php-zip -y \
        && apt install wget curl -y
ENV variabletest test

RUN apt install vim -y
# RUN wget -O /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz
# WORKDIR /var/www/html
# RUN tar -xzvf /tmp/wordpress.tar.gz -C /var/www/html
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
WORKDIR /var/www/html
RUN wp core download --allow-root
RUN sed -i "s|database_name_here|$HOME|" wp-config-sample.php
RUN env > file.test
# RUN wp config create --dbname=testname --dbuser=testuser --dbpass=testpass --allow-root

