FROM debian:buster 

RUN apt update && apt install nginx openssl -y 

# RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
# -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt \
# -subj "$SUBJ"

RUN rm /etc/nginx/sites-enabled/default 
COPY tools/nginx.conf /etc/nginx/sites-enabled/
COPY tools/script.sh /
RUN chmod +x script.sh


ENTRYPOINT [ "/script.sh" ]

