FROM debian:buster 

RUN apt update && apt install nginx openssl -y 
RUN rm /etc/nginx/sites-enabled/default 
COPY tools/nginx.conf /etc/nginx/sites-enabled/
COPY tools/script.sh /
RUN chmod +x script.sh


ENTRYPOINT [ "/script.sh" ]

