FROM debian:buster

RUN apt update && apt install mariadb-server -y
RUN apt install vim -y
# RUN apt install systemctl -y
# RUN systemctl enable mysql
# RUN apt install systemctl -y

# RUN UPDATE mysql.user SET authentication_string=PASSWORD('hadapassword') WHERE User='root';